[package]
name = "gbc-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gameboy = { path = "../gameboy" }
climg = { path = "./climg" }
rayon = "1.6.1"
crossterm = "0.28.1"
