[package]
name = "roms"
version = "0.1.0"
edition = "2024"

[build-dependencies]
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"

[dependencies]
serde_json = { version = "1.0", optional = true }
